// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace musicapp.Models
{
    public partial class Feedback1
    {
        public int Feedid { get; set; }
        public string Songname { get; set; }
        public string Email { get; set; }
        public string Feedback { get; set; }

        public virtual User EmailNavigation { get; set; }
    }
}