// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace musicapp.Models
{
    public partial class Genre
    {
        public Genre()
        {
            Musics = new HashSet<Music>();
        }

        public int Genreid { get; set; }
        public string Genrename { get; set; }

        public virtual ICollection<Music> Musics { get; set; }
    }
}