// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace musicapp.Models
{
    public partial class Voting
    {
        public int? Songid { get; set; }
        public string Email { get; set; }
        public int Voteid { get; set; }

        public virtual User EmailNavigation { get; set; }
        public virtual Music Song { get; set; }
    }
}